name = "BolteXD"
author = "BolteXD"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05605bb8b0130b909f0fdb0976330cfb835d762d4450e3ccbb8c690645e65c21"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
