name = "BolteXD"
author = "BolteXD"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "391861685981f4a619e08f69db2f314641a5a47420f5b0e50633e141a42c1729"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
