name = "BolteXD"
author = "BolteXD"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36b46fd463d15de11f029f3398076380afe06a9dc9e2971a1db2767d0917e764"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
