name = "BolteXD"
author = "BolteXD"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a3465df244fcc16e519adec8bdb067e67e4175148034ee5f0283e0353b5d273"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
