name = "BolteXD"
author = "BolteXD"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b9bd9e894c915e117cafc8be2618cdb82bd00115e5f2c2fe6603292ad5a8333"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
