name = "Fusion"
author = "Bolte"
version = "0.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23733712c95e3c7f46ca23bb45569960ed6da9050cb07cc79e4f00bce25b7c38"

[versions]
forge = "14.23.0.2486"
minecraft = "1.12.2"
