name = "Fusion"
author = "Bolte"
version = "0.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eef899dbdcbc9668579dc45dc7c6a7d8c7fe4bd8421c5e4cc1e11c814873e2d2"

[versions]
forge = "14.23.0.2486"
minecraft = "1.12.2"
