name = "BolteXD"
author = "BolteXD"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff4bfd7481a2bb2c679191c79bdf0fb6731687d62eb7f9062dad93100900e738"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
