name = "BolteXD"
author = "BolteXD"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5286ca6cca169d0f82d7bf7d01da7b177ade42b267f485b3caaa5e877c7fa437"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
