name = "Mixin 0.7-0.8 Compatibility"
filename = "%5B___MixinCompat-0.8___%5D.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3045/381/%5B___MixinCompat-0.8___%5D.jar"
hash-format = "murmur2"
hash = "89892035"

[update]
[update.curseforge]
file-id = 3045381
project-id = 405327
