name = "ModDirector"
filename = "mod-director-launchwrapper-1.4-SNAPSHOT-all.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2980/239/mod-director-launchwrapper-1.4-SNAPSHOT-all.jar"
hash-format = "murmur2"
hash = "2256867456"

[update]
[update.curseforge]
file-id = 2980239
project-id = 367103
release-channel = "beta"
