name = "Multithreaded Noise"
filename = "MultithreadedNoise-1.12.2-0.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2642/103/MultithreadedNoise-1.12.2-0.0.2.jar"
hash-format = "murmur2"
hash = "2182668655"

[update]
[update.curseforge]
file-id = 2642103
project-id = 307843
