name = "OPTIFINE ALBEHERO"
filename = "OptiFine_1.12.2_HD_U_G5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3253/803/OptiFine_1.12.2_HD_U_G5.jar"
hash-format = "murmur2"
hash = "43417211"

[update]
[update.curseforge]
file-id = 3253803
project-id = 462460
