name = "Performant"
filename = "performant-1.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3511/568/performant-1.11.jar"
hash-format = "murmur2"
hash = "1065102291"

[update]
[update.curseforge]
file-id = 3511568
project-id = 354143
