name = "Pick Up Notifier [Forge]"
filename = "PickUpNotifier-v1.1.5-1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3062/121/PickUpNotifier-v1.1.5-1.12.2.jar"
hash-format = "murmur2"
hash = "2268160889"

[update]
[update.curseforge]
file-id = 3062121
project-id = 351441
